# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wedgeblock.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='wedgeblock.proto',
  package='wedgeblock',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10wedgeblock.proto\x12\nwedgeblock\"R\n\x0bTransaction\x12\x0b\n\x03key\x18\x01 \x01(\x0c\x12\x0b\n\x03val\x18\x02 \x01(\x0c\x12\x16\n\x0esequenceNumber\x18\x03 \x01(\x05\x12\x11\n\tsignature\x18\x04 \x01(\x0c\"<\n\x10TransactionBatch\x12(\n\x07\x63ontent\x18\x01 \x03(\x0b\x32\x17.wedgeblock.Transaction\"\xb8\x01\n\x05Hash1\x12\x10\n\x08logIndex\x18\x01 \x01(\x05\x12\x12\n\nmerkleRoot\x18\x02 \x01(\x0c\x12\x17\n\x0fmerkleProofPath\x18\x03 \x03(\x0c\x12\x16\n\x0emerkleProofDir\x18\x04 \x03(\x05\x12\x13\n\x0bmerkleProof\x18\x05 \x01(\x0c\x12\x0b\n\x03key\x18\x06 \x01(\x0c\x12\x0b\n\x03val\x18\x07 \x01(\x0c\x12\x16\n\x0esequenceNumber\x18\x08 \x01(\x05\x12\x11\n\trawTxnStr\x18\t \x01(\t\"G\n\rHash1Response\x12\x1d\n\x02h1\x18\x01 \x01(\x0b\x32\x11.wedgeblock.Hash1\x12\x17\n\x0f\x65thMsgSignature\x18\x02 \x01(\x0c\"@\n\x12Hash1ResponseBatch\x12*\n\x07\x63ontent\x18\x01 \x03(\x0b\x32\x19.wedgeblock.Hash1Response\"/\n\x07LogHash\x12\x10\n\x08logIndex\x18\x01 \x01(\x05\x12\x12\n\nmerkleRoot\x18\x02 \x01(\x0c\"A\n\x05Hash2\x12\x0f\n\x07TxnHash\x18\x01 \x01(\x0c\x12\'\n\x06status\x18\x02 \x01(\x0e\x32\x17.wedgeblock.Hash2Status\"-\n\nQueryBatch\x12\x0c\n\x04keys\x18\x02 \x03(\x0c\x12\x11\n\tsignature\x18\x03 \x01(\x0c\"5\n\x0c\x41uditRequest\x12\x12\n\nlogIndexes\x18\x01 \x03(\x05\x12\x11\n\tsignature\x18\x02 \x01(\x0c*4\n\x0bHash2Status\x12\x0b\n\x07INVALID\x10\x00\x12\r\n\tNOT_READY\x10\x01\x12\t\n\x05VALID\x10\x02\x32\xde\x02\n\x08\x45\x64geNode\x12=\n\x07\x45xecute\x12\x17.wedgeblock.Transaction\x1a\x19.wedgeblock.Hash1Response\x12I\n\x0c\x45xecuteBatch\x12\x1c.wedgeblock.TransactionBatch\x1a\x19.wedgeblock.Hash1Response0\x01\x12\x37\n\rGetPhase2Hash\x12\x13.wedgeblock.LogHash\x1a\x11.wedgeblock.Hash2\x12\x42\n\x0b\x41nswerQuery\x12\x16.wedgeblock.QueryBatch\x1a\x19.wedgeblock.Hash1Response0\x01\x12K\n\x12\x41nswerFullLogAudit\x12\x18.wedgeblock.AuditRequest\x1a\x19.wedgeblock.Hash1Response0\x01\x62\x06proto3'
)

_HASH2STATUS = _descriptor.EnumDescriptor(
  name='Hash2Status',
  full_name='wedgeblock.Hash2Status',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='INVALID', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='NOT_READY', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='VALID', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=722,
  serialized_end=774,
)
_sym_db.RegisterEnumDescriptor(_HASH2STATUS)

Hash2Status = enum_type_wrapper.EnumTypeWrapper(_HASH2STATUS)
INVALID = 0
NOT_READY = 1
VALID = 2



_TRANSACTION = _descriptor.Descriptor(
  name='Transaction',
  full_name='wedgeblock.Transaction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='wedgeblock.Transaction.key', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='val', full_name='wedgeblock.Transaction.val', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sequenceNumber', full_name='wedgeblock.Transaction.sequenceNumber', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='signature', full_name='wedgeblock.Transaction.signature', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=114,
)


_TRANSACTIONBATCH = _descriptor.Descriptor(
  name='TransactionBatch',
  full_name='wedgeblock.TransactionBatch',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='content', full_name='wedgeblock.TransactionBatch.content', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=116,
  serialized_end=176,
)


_HASH1 = _descriptor.Descriptor(
  name='Hash1',
  full_name='wedgeblock.Hash1',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='logIndex', full_name='wedgeblock.Hash1.logIndex', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='merkleRoot', full_name='wedgeblock.Hash1.merkleRoot', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='merkleProofPath', full_name='wedgeblock.Hash1.merkleProofPath', index=2,
      number=3, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='merkleProofDir', full_name='wedgeblock.Hash1.merkleProofDir', index=3,
      number=4, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='merkleProof', full_name='wedgeblock.Hash1.merkleProof', index=4,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='key', full_name='wedgeblock.Hash1.key', index=5,
      number=6, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='val', full_name='wedgeblock.Hash1.val', index=6,
      number=7, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sequenceNumber', full_name='wedgeblock.Hash1.sequenceNumber', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='rawTxnStr', full_name='wedgeblock.Hash1.rawTxnStr', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=179,
  serialized_end=363,
)


_HASH1RESPONSE = _descriptor.Descriptor(
  name='Hash1Response',
  full_name='wedgeblock.Hash1Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='h1', full_name='wedgeblock.Hash1Response.h1', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ethMsgSignature', full_name='wedgeblock.Hash1Response.ethMsgSignature', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=365,
  serialized_end=436,
)


_HASH1RESPONSEBATCH = _descriptor.Descriptor(
  name='Hash1ResponseBatch',
  full_name='wedgeblock.Hash1ResponseBatch',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='content', full_name='wedgeblock.Hash1ResponseBatch.content', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=438,
  serialized_end=502,
)


_LOGHASH = _descriptor.Descriptor(
  name='LogHash',
  full_name='wedgeblock.LogHash',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='logIndex', full_name='wedgeblock.LogHash.logIndex', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='merkleRoot', full_name='wedgeblock.LogHash.merkleRoot', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=504,
  serialized_end=551,
)


_HASH2 = _descriptor.Descriptor(
  name='Hash2',
  full_name='wedgeblock.Hash2',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='TxnHash', full_name='wedgeblock.Hash2.TxnHash', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='status', full_name='wedgeblock.Hash2.status', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=553,
  serialized_end=618,
)


_QUERYBATCH = _descriptor.Descriptor(
  name='QueryBatch',
  full_name='wedgeblock.QueryBatch',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='keys', full_name='wedgeblock.QueryBatch.keys', index=0,
      number=2, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='signature', full_name='wedgeblock.QueryBatch.signature', index=1,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=620,
  serialized_end=665,
)


_AUDITREQUEST = _descriptor.Descriptor(
  name='AuditRequest',
  full_name='wedgeblock.AuditRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='logIndexes', full_name='wedgeblock.AuditRequest.logIndexes', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='signature', full_name='wedgeblock.AuditRequest.signature', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=667,
  serialized_end=720,
)

_TRANSACTIONBATCH.fields_by_name['content'].message_type = _TRANSACTION
_HASH1RESPONSE.fields_by_name['h1'].message_type = _HASH1
_HASH1RESPONSEBATCH.fields_by_name['content'].message_type = _HASH1RESPONSE
_HASH2.fields_by_name['status'].enum_type = _HASH2STATUS
DESCRIPTOR.message_types_by_name['Transaction'] = _TRANSACTION
DESCRIPTOR.message_types_by_name['TransactionBatch'] = _TRANSACTIONBATCH
DESCRIPTOR.message_types_by_name['Hash1'] = _HASH1
DESCRIPTOR.message_types_by_name['Hash1Response'] = _HASH1RESPONSE
DESCRIPTOR.message_types_by_name['Hash1ResponseBatch'] = _HASH1RESPONSEBATCH
DESCRIPTOR.message_types_by_name['LogHash'] = _LOGHASH
DESCRIPTOR.message_types_by_name['Hash2'] = _HASH2
DESCRIPTOR.message_types_by_name['QueryBatch'] = _QUERYBATCH
DESCRIPTOR.message_types_by_name['AuditRequest'] = _AUDITREQUEST
DESCRIPTOR.enum_types_by_name['Hash2Status'] = _HASH2STATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Transaction = _reflection.GeneratedProtocolMessageType('Transaction', (_message.Message,), {
  'DESCRIPTOR' : _TRANSACTION,
  '__module__' : 'wedgeblock_pb2'
  # @@protoc_insertion_point(class_scope:wedgeblock.Transaction)
  })
_sym_db.RegisterMessage(Transaction)

TransactionBatch = _reflection.GeneratedProtocolMessageType('TransactionBatch', (_message.Message,), {
  'DESCRIPTOR' : _TRANSACTIONBATCH,
  '__module__' : 'wedgeblock_pb2'
  # @@protoc_insertion_point(class_scope:wedgeblock.TransactionBatch)
  })
_sym_db.RegisterMessage(TransactionBatch)

Hash1 = _reflection.GeneratedProtocolMessageType('Hash1', (_message.Message,), {
  'DESCRIPTOR' : _HASH1,
  '__module__' : 'wedgeblock_pb2'
  # @@protoc_insertion_point(class_scope:wedgeblock.Hash1)
  })
_sym_db.RegisterMessage(Hash1)

Hash1Response = _reflection.GeneratedProtocolMessageType('Hash1Response', (_message.Message,), {
  'DESCRIPTOR' : _HASH1RESPONSE,
  '__module__' : 'wedgeblock_pb2'
  # @@protoc_insertion_point(class_scope:wedgeblock.Hash1Response)
  })
_sym_db.RegisterMessage(Hash1Response)

Hash1ResponseBatch = _reflection.GeneratedProtocolMessageType('Hash1ResponseBatch', (_message.Message,), {
  'DESCRIPTOR' : _HASH1RESPONSEBATCH,
  '__module__' : 'wedgeblock_pb2'
  # @@protoc_insertion_point(class_scope:wedgeblock.Hash1ResponseBatch)
  })
_sym_db.RegisterMessage(Hash1ResponseBatch)

LogHash = _reflection.GeneratedProtocolMessageType('LogHash', (_message.Message,), {
  'DESCRIPTOR' : _LOGHASH,
  '__module__' : 'wedgeblock_pb2'
  # @@protoc_insertion_point(class_scope:wedgeblock.LogHash)
  })
_sym_db.RegisterMessage(LogHash)

Hash2 = _reflection.GeneratedProtocolMessageType('Hash2', (_message.Message,), {
  'DESCRIPTOR' : _HASH2,
  '__module__' : 'wedgeblock_pb2'
  # @@protoc_insertion_point(class_scope:wedgeblock.Hash2)
  })
_sym_db.RegisterMessage(Hash2)

QueryBatch = _reflection.GeneratedProtocolMessageType('QueryBatch', (_message.Message,), {
  'DESCRIPTOR' : _QUERYBATCH,
  '__module__' : 'wedgeblock_pb2'
  # @@protoc_insertion_point(class_scope:wedgeblock.QueryBatch)
  })
_sym_db.RegisterMessage(QueryBatch)

AuditRequest = _reflection.GeneratedProtocolMessageType('AuditRequest', (_message.Message,), {
  'DESCRIPTOR' : _AUDITREQUEST,
  '__module__' : 'wedgeblock_pb2'
  # @@protoc_insertion_point(class_scope:wedgeblock.AuditRequest)
  })
_sym_db.RegisterMessage(AuditRequest)



_EDGENODE = _descriptor.ServiceDescriptor(
  name='EdgeNode',
  full_name='wedgeblock.EdgeNode',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=777,
  serialized_end=1127,
  methods=[
  _descriptor.MethodDescriptor(
    name='Execute',
    full_name='wedgeblock.EdgeNode.Execute',
    index=0,
    containing_service=None,
    input_type=_TRANSACTION,
    output_type=_HASH1RESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='ExecuteBatch',
    full_name='wedgeblock.EdgeNode.ExecuteBatch',
    index=1,
    containing_service=None,
    input_type=_TRANSACTIONBATCH,
    output_type=_HASH1RESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetPhase2Hash',
    full_name='wedgeblock.EdgeNode.GetPhase2Hash',
    index=2,
    containing_service=None,
    input_type=_LOGHASH,
    output_type=_HASH2,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='AnswerQuery',
    full_name='wedgeblock.EdgeNode.AnswerQuery',
    index=3,
    containing_service=None,
    input_type=_QUERYBATCH,
    output_type=_HASH1RESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='AnswerFullLogAudit',
    full_name='wedgeblock.EdgeNode.AnswerFullLogAudit',
    index=4,
    containing_service=None,
    input_type=_AUDITREQUEST,
    output_type=_HASH1RESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_EDGENODE)

DESCRIPTOR.services_by_name['EdgeNode'] = _EDGENODE

# @@protoc_insertion_point(module_scope)
